### ISSUE TITLE
Investigate use of enums in function calls

### ISSUE THREAD

**Issue by Seizure** [Seizure/MonitorBoss#22]
better to provide helper functions which can translate them and check if they are known/"valid"? Or perhaps provide "safe" and "unsafe" options? Idk

**Comment by Rangi42** [comment]
Replaced by https://github.com/Seizure/MonitorBoss/issues/22.

**Comment by Seizure** [comment]
VCP functions now accept VCPCode class objects, along with an int value (which can be retrieved from/checked against the class's enum, if applicable)
