### ISSUE TITLE
Make program internals lowercase

### ISSUE THREAD

**Issue by Seizure** [Seizure/MonitorBoss#6]
currently, case matters in quite a few areas of the program, which forces us to do weird things, like making ConfigParser case-sensitive (so that it doesn't change the case of aliases and etc on us).

**Comment by Rangi42** [comment]
Alternatively, switch to lowercase and leave it case-sensitive.

e.g. you can do `ddcutil detect` but not `ddcutil DETECT` (and of course not `DDCUTIL detect`).

We may have to translate some `monitorcontrol` enums into lowercase.
